#!/bin/bash

hc() {
    herbstclient "$@"
}

hc emit_hook reload

hc keyunbind --all
hc mouseunbind --all

# tags
tag_names=( {1..8} )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
done

# mouse
# hc mousebind $Mod-Button1 move
# hc mousebind $Mod-Button2 zoom
# hc mousebind $Mod-Button3 resize

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

hc set frame_border_active_color '#504945'
hc set frame_border_normal_color '#282828'
hc set frame_bg_active_color '#3c3836'
hc set frame_bg_normal_color '#3c3836'
hc set frame_border_width 0
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 5
hc set frame_gap 13

hc attr theme.active.color '#d65d0e'
hc attr theme.normal.color '#282828'
# hc attr theme.urgent.color orange
hc attr theme.inner_width 0
# hc attr theme.inner_color black
hc attr theme.border_width 4
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
# hc attr theme.floating.outer_color black
# hc attr theme.active.inner_color '#3E4A00'
# hc attr theme.active.outer_color '#3E4A00'
# hc attr theme.background_color '#141414'

hc set window_gap 0
hc set frame_padding 2
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

# rules
hc unrule -F

#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc rule class="Tint2" manage=off focus=off
hc rule class="Tint2" manage=off focus=off
hc rule class=tint2 manage=off focus=off
hc rule class=tint2 manage=off focus=off

hc rule class="Studio 5.exe" manage=off focus=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors
hc pad 0 0 0 0 40

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
done
